"""phase3_interview_invites

Revision ID: 9b77d4a12557
Revises: 4fa4fbd8f03d
Create Date: 2026-09-06 17:34:56.456377
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '9b77d4a12557'
down_revision: Union[str, None] = '4fa4fbd8f03d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_invites',
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'opened', 'accepted', 'completed', 'expired', 'revoked', name='invite_status', native_enum=False, length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_interview_invite_token_hash')
    )
    op.create_index(op.f('ix_interview_invites_interview_id'), 'interview_invites', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_invites_status'), 'interview_invites', ['status'], unique=False)
    op.create_index(op.f('ix_interview_invites_token_hash'), 'interview_invites', ['token_hash'], unique=False)
    op.add_column(
        'interviews',
        sa.Column(
            'expected_duration_seconds',
            sa.Integer(),
            nullable=False,
            server_default='480',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'expected_duration_seconds')
    op.drop_index(op.f('ix_interview_invites_token_hash'), table_name='interview_invites')
    op.drop_index(op.f('ix_interview_invites_status'), table_name='interview_invites')
    op.drop_index(op.f('ix_interview_invites_interview_id'), table_name='interview_invites')
    op.drop_table('interview_invites')
    # ### end Alembic commands ###
